# Generated by Django 5.0.6 on 2024-11-28 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='Perk')),
                ('num_value', models.IntegerField(verbose_name='Number value')),
                ('bool_value', models.BooleanField(verbose_name='Boolean value')),
            ],
            options={
                'verbose_name': 'Perk',
                'verbose_name_plural': 'Perks',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug for internal use')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the ship')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('cargo_weight', models.IntegerField(verbose_name='Cargo Weight')),
                ('cargo_volume', models.IntegerField(verbose_name='Cargo Volume')),
                ('range', models.IntegerField(verbose_name='Range')),
            ],
            options={
                'verbose_name': 'Ship',
                'verbose_name_plural': 'Ships',
            },
        ),
        migrations.CreateModel(
            name='UserShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_mission', models.BooleanField(default=False, verbose_name='On mission')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='ships.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Players ship',
                'verbose_name_plural': 'Players ships',
            },
        ),
    ]
