# Generated by Django 5.0.6 on 2025-02-16 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perk',
            name='bool_value',
        ),
        migrations.RemoveField(
            model_name='perk',
            name='num_value',
        ),
        migrations.RemoveField(
            model_name='perk',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='cargo_volume',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='cargo_weight',
        ),
        migrations.AddField(
            model_name='perk',
            name='ad_text',
            field=models.TextField(default='', verbose_name='Ad Text'),
        ),
        migrations.AddField(
            model_name='perk',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='perk',
            name='type',
            field=models.CharField(choices=[('PERM', 'Permanent'), ('DISP', 'Disposable'), ('1TIME', 'One-timer'), ('RENT', 'Rent')], default='PERM', max_length=5, verbose_name='Perk type'),
        ),
        migrations.AddField(
            model_name='ship',
            name='cargo_hold',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Cargo Hold'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='perks',
            field=models.ManyToManyField(related_name='ships_with_perks', to='ships.perk', verbose_name='Perks'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='range',
            field=models.PositiveSmallIntegerField(verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='usership',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_users', to='ships.ship'),
        ),
        migrations.AlterField(
            model_name='usership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ships', to=settings.AUTH_USER_MODEL),
        ),
    ]
