# Generated by Django 5.0.6 on 2025-02-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_remove_perk_bool_value_remove_perk_num_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='perks',
        ),
    ]
