# Generated by Django 5.0.6 on 2024-10-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_alter_ships_options_alter_ships_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ships',
            new_name='Ship',
        ),
    ]
