# Generated by Django 5.0.6 on 2024-11-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0004_usership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name': 'Ship', 'verbose_name_plural': 'List of Ships'},
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='size',
        ),
        migrations.AddField(
            model_name='ship',
            name='cargo_volume',
            field=models.IntegerField(default=10, verbose_name='Cargo Volume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='cargo_weight',
            field=models.IntegerField(default=100, verbose_name='Cargo Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ship',
            name='range',
            field=models.IntegerField(default=10, verbose_name='Range'),
            preserve_default=False,
        ),
    ]
