# Generated by Django 5.0.6 on 2025-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0004_shipperks_ship_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='perks',
            field=models.ManyToManyField(related_name='ships_with_perk', through='ships.ShipPerks', to='ships.perk'),
        ),
    ]
