# Generated by Django 5.0.6 on 2025-02-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0005_alter_ship_perks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipperks',
            unique_together={('ship', 'perk')},
        ),
    ]
