# Generated by Django 5.0.6 on 2025-02-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0006_alter_shipperks_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShipPerks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Amount')),
                ('perk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.perk')),
                ('user_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.usership')),
            ],
            options={
                'unique_together': {('user_ship', 'perk')},
            },
        ),
    ]
