# Generated by Django 5.0.6 on 2025-02-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0007_usershipperks'),
    ]

    operations = [
        migrations.AddField(
            model_name='usership',
            name='perks',
            field=models.ManyToManyField(related_name='user_ships_with_perk', through='ships.UserShipPerks', to='ships.perk'),
        ),
    ]
