# Generated by Django 5.0.6 on 2025-02-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0008_usership_perks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='perks',
            field=models.ManyToManyField(through='ships.ShipPerks', to='ships.perk'),
        ),
        migrations.AlterField(
            model_name='shipperks',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships_with_perk', to='ships.perk'),
        ),
        migrations.AlterField(
            model_name='shipperks',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships_perks', to='ships.ship'),
        ),
    ]
