# Generated by Django 5.0.6 on 2025-02-16 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0009_alter_ship_perks_alter_shipperks_perk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperks',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_perks', to='ships.ship'),
        ),
    ]
