# Generated by Django 5.0.6 on 2025-02-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0010_alter_shipperks_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershipperks',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usership_with_perk', to='ships.perk'),
        ),
        migrations.AlterField(
            model_name='usershipperks',
            name='user_ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usership_perks', to='ships.usership'),
        ),
    ]
