# Generated by Django 5.0.6 on 2025-02-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0011_alter_usershipperks_perk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipperks',
            old_name='amount',
            new_name='default_amount',
        ),
        migrations.RenameField(
            model_name='usershipperks',
            old_name='amount',
            new_name='owned_amount',
        ),
    ]
