# Generated by Django 5.0.6 on 2025-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0013_alter_usershipperks_owned_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usershipperks',
            unique_together=set(),
        ),
    ]
