# Generated by Django 5.0.6 on 2025-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0014_alter_usershipperks_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
