# Generated by Django 5.0.6 on 2024-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_delete_userresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='quantium',
            field=models.PositiveIntegerField(verbose_name='Quantiums'),
        ),
    ]
