# Generated by Django 5.0.6 on 2024-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=128, verbose_name='Codename')),
                ('expansion', models.CharField(max_length=128, verbose_name='Expansion')),
                ('reward', models.IntegerField(verbose_name='Reward')),
                ('summary', models.CharField(max_length=400, verbose_name='Summary')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('distance', models.IntegerField(verbose_name='Distance')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('weight', models.IntegerField(verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'List of Missions',
            },
        ),
    ]
