# Generated by Django 5.0.6 on 2024-10-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missions',
            options={'verbose_name': 'Mission', 'verbose_name_plural': 'List of Missions'},
        ),
    ]
