# Generated by Django 5.0.6 on 2025-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='weight',
        ),
        migrations.AddField(
            model_name='mission',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
