# Generated by Django 5.0.6 on 2024-11-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_missions_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missions',
            name='title',
        ),
        migrations.AddField(
            model_name='missions',
            name='codename',
            field=models.CharField(default=10, max_length=128, verbose_name='Codename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='distance',
            field=models.IntegerField(default=10, verbose_name='Distance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='duration',
            field=models.IntegerField(default=10, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='expansion',
            field=models.CharField(default=10, max_length=128, verbose_name='Expansion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='reward',
            field=models.IntegerField(default=10, verbose_name='Reward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='summary',
            field=models.CharField(default=10, max_length=400, verbose_name='Summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='volume',
            field=models.IntegerField(default=10, verbose_name='Volume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missions',
            name='weight',
            field=models.IntegerField(default=10, verbose_name='Weight'),
            preserve_default=False,
        ),
    ]
