# Generated by Django 5.0.6 on 2024-11-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_remove_missions_title_missions_codename_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Missions',
            new_name='Mission',
        ),
    ]
