# Generated by Django 5.0.6 on 2024-11-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='quantium',
        ),
    ]
