# Generated by Django 5.0.6 on 2024-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='player',
            name='datacoins',
            field=models.PositiveIntegerField(default=0, verbose_name='Datacoins'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
